// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDtgtWUxk5inDmSJkxsaKJfMw7-8mP2Jg',
    appId: '1:618215022170:web:8b7fa977cafffb2f6cc263',
    messagingSenderId: '618215022170',
    projectId: 'liahona-quiz',
    authDomain: 'liahona-quiz.firebaseapp.com',
    storageBucket: 'liahona-quiz.firebasestorage.app',
    measurementId: 'G-K6LNT8FMQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjFMnhE7ZVCzHC5GvSLW1MIrgC_RqcqaY',
    appId: '1:618215022170:android:996fb0e1e8d66f5c6cc263',
    messagingSenderId: '618215022170',
    projectId: 'liahona-quiz',
    storageBucket: 'liahona-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqVFOSK66cBs9mVpJEhPTlMEFXFjLPn9Q',
    appId: '1:618215022170:ios:e43eb7da340bbb456cc263',
    messagingSenderId: '618215022170',
    projectId: 'liahona-quiz',
    storageBucket: 'liahona-quiz.firebasestorage.app',
    iosBundleId: 'com.example.quizSud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqVFOSK66cBs9mVpJEhPTlMEFXFjLPn9Q',
    appId: '1:618215022170:ios:e43eb7da340bbb456cc263',
    messagingSenderId: '618215022170',
    projectId: 'liahona-quiz',
    storageBucket: 'liahona-quiz.firebasestorage.app',
    iosBundleId: 'com.example.quizSud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDtgtWUxk5inDmSJkxsaKJfMw7-8mP2Jg',
    appId: '1:618215022170:web:537cc8e931b75dda6cc263',
    messagingSenderId: '618215022170',
    projectId: 'liahona-quiz',
    authDomain: 'liahona-quiz.firebaseapp.com',
    storageBucket: 'liahona-quiz.firebasestorage.app',
    measurementId: 'G-QDHC97C0HH',
  );
}
