name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 1. Instala o Flutter do zero no servidor do GitHub
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      # 2. Baixa as dependências
      - run: flutter pub get
      
      # 3. COMPILA o código novo (É isso aqui que garante que sua alteração visual vá para o ar)
      - run: flutter build web --release
      
      # 4. Faz o upload da nova versão para o Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIAHONA_QUIZ }}
          channelId: live
          projectId: liahona-quiz