name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Passo 1: Instalar o Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      # Passo 2: Instalar dependências
      - run: flutter pub get
      
      # Passo 3: Build do Web
      - run: flutter build web --release
      
      # Passo 4: Deploy para o Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIAHONA_QUIZ }}
          channelId: live
          projectId: liahona-quiz
          # Removemos o channelId: live para ver se ele para de tentar fazer o "release" forçado